---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Projects/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .vimrc

apt_packages:
  ## CLI Applications
  - autoconf
  - bash-completion
  #- bat
  - ctop
  - docker.io
  - docker-compose
  - git
  - gitk
  - golang
  - htop
  #- mkcert
  - mysql-client
  - nmap
  - nodejs
  #- ssh-copy-id
  - openssh-client
  - readline-common
  - openssl
  - packer
  - pv
  #- terraform
  - tig
  - tree
  - procps
  
  ## GUI Applications 
  #- 1password
  #- appcode
  #- battle-net
  #- dash
  #- datagrip
  - firefox
  #- gitify
  - chromium-browser
  #- intellij
  #- java
  - mysql-workbench
  #- phpstorm
  #- postman
  #- pycharm
  #- skype
  #- slack
  #- spotify
  #- steam
  #- sublime-text
  - telegram-desktop
  - vagrant
  - virtualbox
  - virtualbox-ext-pack
  #- visual-studio-code
  #- vlc
  #- whatsapp
  - wireshark

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
