---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes

dotfiles_repo: https://github.com/omissis/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Projects/GitHub/dotfiles
dotfiles_files:
  - .aliases
  - .gitconfig
  - .gitignore
  - .inputrc
  - .vimrc
  - .zshrc

apt_packages:
  ## CLI Applications
  - apt-transport-https
  - autoconf
  - bash-completion
  - bcmwl-kernel-source
  - ctop
  - docker-compose
  - docker.io
  - git
  - gitk
  - gnupg2
  - golang
  - htop
  - libnss3-tools
  - mysql-client
  - nmap
  - nodejs
  - openssh-client
  - openssl
  - packer
  - procps
  - pv
  - readline-common
  - software-properties-common
  - tig
  - tree
  - vim
  - zsh

  ## GUI Applications 
  #- 1passwordX
  #- gitify # https://www.gitify.io/
  - albert
  - chromium-browser
  - copyq
  - guake
  - steam-installer
  - telegram-desktop
  - vagrant
  - virtualbox
  - wireshark

apt_repositories:
  - repo: 'deb https://download.virtualbox.org/virtualbox/debian bionic contrib'
    key: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
  - repo: 'deb http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com bionic main'
    key: 'https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc'
  - repo: 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04/ /'
    key: 'https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_20.04/Release.key'
  - repo: 'ppa:hluk/copyq'

snap_packages:
  - 1password
  - mysql-workbench-community
  - postman
  - spotify
  - vlc
  - whatsdesk

snap_classic_packages:
  - code
  - skype
  - slack
  - sublime-text

# manual installations
# - [ ] Browser extensions (1PasswordX)
# - [ ] JetBrains Products
# - [ ] Hashicorp Products (Terraform, Vagrant, Packer)
# - [ ] mkcert, oh-my-zsh, oh-my-zsh plugins
# - [ ] kinto.sh
# - [ ] linux brew
# - [ ] zsh plugins
#   - [ ] git clone https://github.com/unixorn/git-extra-commands.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/git-extra-commands
#   - [ ] git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
#   - [ ] git clone git@github.com:zsh-users/zsh-history-substring-search.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search
#   - [ ] git clone git@github.com:zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
