---

# Setup direnv as per https://blog.sighup.io/manage-tools-with-ease-direnv-asdf/

- name: Allow direnv execution in home directory
  command:
    cmd: "{{ asdf_bin }} exec direnv allow"
    chdir: "{{ lookup('env','HOME') }}"
  become: false
